[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "text/plain"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/work/*"
  function = "middleware"

[dev]
  framework = "astro" 